### ISSUE TITLE
Bulk operations for garbage collection schedule

### ISSUE THREAD

**Issue by simvadnbu** [SELab-2/Dr-Trottoir-4#358]
![image](https://user-images.githubusercontent.com/77171450/233932813-bf04754d-d2ef-4f11-9f9e-1e8ffb648e6f.png)

A post-endpoint with example body:
```
{
garbage_type: string,
date: Date,
move_to_date: Date,
region/tour : id
}
```

**Comment by TiboStr** [comment]
So the purpose of this issue is to create an endpoint to **move all entities in the table garbage_collection** with a **given garbage_type, date and tour** to a **different given date**?

Why does it say `region/tour` and not just `tour` or `region`? Is a decision yet to be made?

**Comment by TiboStr** [comment]
To reschedule a set of `garbage_collection`s, you could do a POST to `http://localhost/api/garbage-collection/bulk-move?garbage_type=PAP&date=2023-03-08&move_to_date=2023-01-11&region=2`

**Comment by simvadnbu** [comment]
> Why does it say `region/tour` and not just `tour` or `region`? Is a decision yet to be made?

It should support both region & tour.
