### ISSUE TITLE
Endpoints analysis

### ISSUE THREAD

**Issue by emneirin** [SELab-2/Dr-Trottoir-4#359]
For the analysis pages the frontend still needs the corresponding endpoints.
How I would see them currently:

- **The worked hours for a students**: on week basis worked hours for all students that worked that week and in which tours (and the expected worked hours)
_Request_ : start date (and end date?)
_Response_ : list per student containing the worked hours, expected worked hours and the tour ids of the tours they've worked

- **Tour analysis**: given a week and tour(id) give the information per building
_Request_ : start date (for week)
_Response_ : list of objects holding the building ids (in order of tour) with the student (id) (student working that tour in that building) the time the student arrived and left, the total time student was present (optional: average time students should be at building)

For **student analysis** we can already get all tours a student has worked given a start and end date with `/student-on-tour/student/{student-id}/`. So given these tours we could do something similar to the above endpoint instead of giving all the students working on that tour int the buildings, we could pass the student's id to that endpoint to only get the times arrived and left, and the total time spend at each building for the specific student.

**Comment by simvadnbu** [comment]
Because tours can be edited, I think it would be best to just analyse the buildings & not the tours. If a tour is changed, the analysis of a tour would not be correct, but you can still receive a list of the buildings the student has done on that day.

**Comment by simvadnbu** [comment]
I think 2 routes are necessary for the analysis:
* An endpoint to get the studentOnTours for a specific period (& optional region filter). Where a working time is given of the whole tour of a `StudentOnTour`. I think a route like this is good: `base_url/analysis/student-on-tour-global?start-date=YYYY-MM-DD&end-date=YYYY-MM-DD&region={id}`.
* An endpoint for an analysis of a specific `StudentOnTour`. More specifically, for each building on a tour calculate the time between arrival (AA) & leaving (VE). The frontend should expect a list like this: 
```
[
{building: $id$, working_time: $minutes$},
...
]
```
An endpoint like this would be sufficient : `base_url/analysis/student-on-tour?student-on-tour={id}`.
