### ISSUE TITLE
Make a view for manuals

### ISSUE THREAD

**Issue by GashinRS** [SELab-2/Dr-Trottoir-4#410]
When you view the information of a building, you should also be able to see its manuals.

--------------------------------------

* [x] Make a manual view
* [x] List all manuals on building info page for admin
* [x] Display most recent manual on building info page for syndic
* [x] Display no manuals for residents
* [ ] On the edit page of admins for buildings, implement functionality to remove manuals and add manuals

**Comment by TiboStr** [comment]
* [ ] Make a manual view
* [ ] List all manuals on building info page for admin
* [ ] Display most recent manual on building info page for syndic
* [ ] Display no manuals for residents
* [ ] On the edit page of admins for buildings, implement functionality to remove manuals and add manuals
