### ISSUE TITLE
frontend styling

### ISSUE THREAD

**Issue by GashinRS** [SELab-2/Dr-Trottoir-4#452]
This includes removing the global styling and making sure individual components look clean, as well as making sure everything is logically placed. One thing some of us have already noticed in that regard is that the current placement for the tours and garbage collections does not make a lot of sense, we could either place these two under a new dropdown in the main header or just directly place both of them on the main header since these will be used a lot.

**Comment by TiboStr** [comment]
Make sure to make links more obvious. E.g. in this example, it is not obvious that there is a link to click:

![Peek 2023-05-16 16-48](https://github.com/SELab-2/Dr-Trottoir-4/assets/71405687/aa41e169-31fc-46a5-9c18-326dc552755d)
