### ISSUE TITLE
Remarks at buildings websocket

### ISSUE THREAD

**Issue by jonathancasters** [SELab-2/Dr-Trottoir-4#471]
Create websockets to update the listeners if there are new remarks.

**Comment by n00bS-oWn-m3** [comment]
I'd also like it if the websocket could return the building id of the building that the student made a remark on. This way, I can also easily use it in the specific admin tour page.
I think you remember this, but just as a clarification, I'm only interested in the "OP" remarks, so it would be useful to either only fire an event for this type, or add the type of the remark to your return body.
