### ISSUE TITLE
Dutch translations missing

### ISSUE THREAD

**Issue by emneirin** [SELab-2/Dr-Trottoir-4#483]
This issue will probably be a thread containing any missing translations

**Comment by emneirin** [comment]
![image](https://github.com/SELab-2/Dr-Trottoir-4/assets/99751639/06f1ee79-c7cd-4167-ab28-c41671606c0c)

**Comment by emneirin** [comment]
![image](https://github.com/SELab-2/Dr-Trottoir-4/assets/99751639/3b3daa6c-fb9a-4e73-9d39-0431b5060e50)

**Comment by sevrijss** [comment]
models.py, StudentOnTour
![image](https://github.com/SELab-2/Dr-Trottoir-4/assets/108656952/150aedfe-1a7c-4d58-ac84-5bfdd979f82c)

**Comment by sevrijss** [comment]
permissions.py
![image](https://github.com/SELab-2/Dr-Trottoir-4/assets/108656952/020200cb-aea8-442d-a2ed-91e3703720fb)

**Comment by jonathancasters** [comment]
**Where?**
`remark_at_building/views.py` , `RemarkAtBuildingIndividualView`, `PATCH`.
**What?**
You can only edit the 'remark' text on a remark at building

**Comment by TiboStr** [comment]
> ![image](https://user-images.githubusercontent.com/99751639/238453138-3b3daa6c-fb9a-4e73-9d39-0431b5060e50.png)

This is done by a library. I cannot control that. However, the library seems to have a translation. It should work.
