### ISSUE TITLE
Tour student bug

### ISSUE THREAD

**Issue by TiboStr** [SELab-2/Dr-Trottoir-4#565]
## Fill in remark
![image](https://github.com/SELab-2/Dr-Trottoir-4/assets/71405687/3b6e4897-8d1b-4fa7-9239-5676a3f770f3)

## Click on next (you see error message that you need at least one image)
![image](https://github.com/SELab-2/Dr-Trottoir-4/assets/71405687/3f5574bc-9b9c-46de-8e64-704af32416c2)

## Upload an image

BUG: that fails

**Comment by TiboStr** [comment]
It succeeds when you click away the error message. I think this is really bad UX, especially on phone.

A fix could be to show the error message in a modal that you *have* to click away. Or you could set a timer and change the error state after e.g. 1 second.

**Comment by simvadnbu** [comment]
I can't seem to replicate this bug.

**Comment by TiboStr** [comment]
I had this issue on the server. Locally I don't seem have this issue. Maybe it was just bad connection. When the server is up and running again, I'll try again.
